// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2us-pwNjy7r6YWxIfaXQ0jM0894jB6ZQ',
    appId: '1:893917100628:web:d278bf6564c80476a10bc1',
    messagingSenderId: '893917100628',
    projectId: 'nguyenvietlam',
    authDomain: 'nguyenvietlam.firebaseapp.com',
    storageBucket: 'nguyenvietlam.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgV5dbat54kP3q4H0fdLi7bUoCbbS41Vs',
    appId: '1:893917100628:android:482c848060f637ada10bc1',
    messagingSenderId: '893917100628',
    projectId: 'nguyenvietlam',
    storageBucket: 'nguyenvietlam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGiuBPE0F5n-h8yq5T1EcRu4FugqJ0UQE',
    appId: '1:893917100628:ios:4e8d61f4f4a7a170a10bc1',
    messagingSenderId: '893917100628',
    projectId: 'nguyenvietlam',
    storageBucket: 'nguyenvietlam.firebasestorage.app',
    iosBundleId: 'com.example.quanlythuvienck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGiuBPE0F5n-h8yq5T1EcRu4FugqJ0UQE',
    appId: '1:893917100628:ios:4e8d61f4f4a7a170a10bc1',
    messagingSenderId: '893917100628',
    projectId: 'nguyenvietlam',
    storageBucket: 'nguyenvietlam.firebasestorage.app',
    iosBundleId: 'com.example.quanlythuvienck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2us-pwNjy7r6YWxIfaXQ0jM0894jB6ZQ',
    appId: '1:893917100628:web:6f8d49d895c57acca10bc1',
    messagingSenderId: '893917100628',
    projectId: 'nguyenvietlam',
    authDomain: 'nguyenvietlam.firebaseapp.com',
    storageBucket: 'nguyenvietlam.firebasestorage.app',
  );

}